name: Deploy Infrastructure

on:
  push:
    branches:
      - development
    paths:
      - "infrastructure/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
      region:
        description: "Azure region to deploy to"
        required: true
        default: "eastus"

env:
  TERRAFORM_VERSION: "1.8.1"
  TERRAGRUNT_VERSION: "0.63.6"
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
  REGION: ${{ github.event.inputs.region || 'eastus' }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_DEV }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_DEV }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_DEV }}

jobs:
  validate:
    name: Validate and Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Check Terraform Installation
        run: |
          which terraform || echo "Terraform not found!"
          terraform version || echo "Failed to get Terraform version!"

      - name: Interact with Terragrunt
        run: terragrunt --version

      - name: Terragrunt init
        working-directory: infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}
        run: |
          terragrunt run-all init --terragrunt-non-interactive | tee terragrunt-init.log

      - name: Terragrunt Validate
        working-directory: infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}
        run: |
          terragrunt run-all validate --terragrunt-non-interactive | tee terragrunt-validate.log

      - name: Terragrunt Plan
        working-directory: infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}
        run: |
          terragrunt run-all plan --terragrunt-non-interactive | tee terragrunt-plan.log

      - name: Save Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: |
            infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}/terragrunt-init.log
            infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}/terragrunt-validate.log
            infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}/terragrunt-plan.log
          retention-days: 1
  apply:
    name: Apply
    needs: validate
    if: github.ref == 'refs/heads/development' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Check Terraform Installation
        run: |
          which terraform || echo "Terraform not found!"
          terraform version || echo "Failed to get Terraform version!"

      - name: Interact with Terragrunt
        run: terragrunt --version

      - name: Terragrunt Init
        working-directory: infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}
        run: |
          terragrunt run-all init -reconfigure --terragrunt-non-interactive | tee terragrunt-init.log

      - name: Terragrunt Apply
        working-directory: infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}
        run: |
          terragrunt run-all apply --terragrunt-non-interactive | tee terragrunt-apply.log

      - name: Save Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-logs
          path: |
            infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}/terragrunt-init.log
            infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.REGION }}/terragrunt-apply.log
          retention-days: 1
