name: Deploy Microservice

on:
  push:
    branches:
      - development
    paths:
      - "mibanco-microservice/**"

jobs:
  deploy:
    uses: ./.github/workflows/microservice-deploy-template.yml
    with:
      microservice_path: "mibanco-microservice"
      acr_name: "mibancodevacr"
      aks_cluster_name: "aks-mibanco-dev"
      aks_resource_group: "rg-mibanco-devops-challenge-dev-eastus"
      namespace: "mibanco-app-ns"
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD_DEV }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
